In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/My Drive/Crime Analysis')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [ ]:
influenced_series_df = pd.read_csv('final_data/influenced_series.csv')
with open('final_data/predict_dicts.pkl', 'rb') as f:
    predict_dicts = pickle.load(f)

In [ ]:
list(predict_dicts.keys())[:10]

['新宿区袋町',
 '新宿区津久戸町',
 '新宿区新宿３丁目',
 '新宿区下落合３丁目',
 '豊島区池袋１丁目',
 '渋谷区東３丁目',
 '新宿区南元町',
 '渋谷区上原３丁目',
 '渋谷区神南２丁目',
 '新宿区高田馬場３丁目']

In [ ]:
list(predict_dicts['新宿区新宿３丁目'].keys())

['新宿区新宿３丁目',
 '新宿区内藤町',
 '新宿区新宿２丁目',
 '新宿区新宿４丁目',
 '新宿区新宿５丁目',
 '新宿区西新宿１丁目',
 '新宿区新宿１丁目',
 '新宿区歌舞伎町１丁目',
 '新宿区歌舞伎町２丁目',
 '新宿区富久町',
 '新宿区西新宿２丁目',
 '新宿区西新宿３丁目',
 '新宿区西新宿６丁目',
 '新宿区西新宿７丁目',
 '渋谷区代々木２丁目',
 '新宿区百人町１丁目',
 '新宿区大久保１丁目',
 '新宿区愛住町',
 '新宿区新宿６丁目',
 '新宿区余丁町',
 '新宿区西新宿４丁目',
 '渋谷区初台１丁目',
 '渋谷区本町１丁目',
 '渋谷区代々木３丁目',
 '渋谷区代々木４丁目',
 '新宿区北新宿２丁目',
 '新宿区北新宿１丁目',
 '新宿区西新宿８丁目']

In [ ]:
influenced_series_df = influenced_series_df.set_index('市区町丁', drop=True)
influenced_series_df.head()

,2022-01-01,2022-01-02,2022-01-03,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-08,2022-01-09,2022-01-10,...,2022-12-22,2022-12-23,2022-12-24,2022-12-25,2022-12-26,2022-12-27,2022-12-28,2022-12-29,2022-12-30,2022-12-31
市区町丁,,,,,,,,,,,,,,,,,,,,,
新宿区袋町,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
新宿区津久戸町,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
新宿区新宿３丁目,1.611216,1.613288,1.607971,1.597013,1.580758,1.559267,1.533018,1.502632,1.468061,1.428071,...,0.798435,0.801273,0.795988,0.777808,0.743218,0.690438,0.619707,0.533239,0.434911,0.329766
新宿区下落合３丁目,0.008271,0.009305,0.010289,0.011168,0.011898,0.012450,0.012807,0.012968,0.012949,0.012771,...,0.010263,0.010056,0.009820,0.009566,0.009309,0.009060,0.008827,0.008616,0.008428,0.008261
豊島区池袋１丁目,0.017087,0.023328,0.029286,0.034640,0.039173,0.042794,0.045534,0.047515,0.048919,0.049933,...,0.044769,0.041826,0.038346,0.034601,0.030847,0.027293,0.024082,0.021292,0.018942,0.017003

In [ ]:
danger_indices_list = []

for index, row in influenced_series_df.iterrows():
    neighbors = list(predict_dicts[row.name].keys())
    mean_values = influenced_series_df.loc[neighbors].mean()
    danger_indices_list.append(mean_values)

danger_indices = pd.DataFrame(danger_indices_list, index=influenced_series_df.index, columns=influenced_series_df.columns)

In [ ]:
danger_indices

,2022-01-01,2022-01-02,2022-01-03,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-08,2022-01-09,2022-01-10,...,2022-12-22,2022-12-23,2022-12-24,2022-12-25,2022-12-26,2022-12-27,2022-12-28,2022-12-29,2022-12-30,2022-12-31
市区町丁,,,,,,,,,,,,,,,,,,,,,
新宿区袋町,0.007152,0.007160,0.007169,0.007180,0.007191,0.007200,0.007208,0.007211,0.007208,0.007197,...,0.007134,0.007139,0.007144,0.007147,0.007150,0.007152,0.007153,0.007153,0.007153,0.007152
新宿区津久戸町,0.008014,0.008023,0.008036,0.008053,0.008073,0.008096,0.008118,0.008139,0.008155,0.008162,...,0.008014,0.008020,0.008025,0.008028,0.008031,0.008033,0.008034,0.008034,0.008034,0.008033
新宿区新宿３丁目,0.283573,0.260230,0.237431,0.216233,0.197370,0.181281,0.168157,0.157952,0.150380,0.144936,...,0.149154,0.148609,0.145625,0.139737,0.130698,0.118526,0.103511,0.086184,0.067265,0.047595
新宿区下落合３丁目,0.045457,0.051643,0.057674,0.063265,0.068213,0.072411,0.075849,0.078587,0.080729,0.082370,...,0.079375,0.075891,0.071711,0.067181,0.062626,0.058309,0.054413,0.051038,0.048210,0.045895
豊島区池袋１丁目,0.057496,0.072404,0.086650,0.099437,0.110231,0.118812,0.125247,0.129827,0.132969,0.135094,...,0.131898,0.124258,0.115032,0.104991,0.094857,0.085218,0.076488,0.068897,0.062507,0.057250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
豊島区池袋本町４丁目,0.042780,0.057975,0.072425,0.085312,0.096095,0.104556,0.110770,0.115042,0.117811,0.119534,...,0.117239,0.108804,0.098988,0.088563,0.078235,0.068566,0.059934,0.052533,0.046395,0.041423
新宿区改代町,0.008532,0.008532,0.008532,0.008533,0.008533,0.008534,0.008536,0.008537,0.008539,0.008541,...,0.008534,0.008534,0.008534,0.008534,0.008534,0.008534,0.008534,0.008534,0.008534,0.008534
新宿区市谷船河原町,0.009718,0.009645,0.009554,0.009449,0.009338,0.009232,0.009146,0.009098,0.009109,0.009202,...,0.009695,0.009702,0.009709,0.009714,0.009717,0.009720,0.009721,0.009722,0.009721,0.009720
新宿区天神町,0.007240,0.007291,0.007339,0.007384,0.007422,0.007453,0.007477,0.007495,0.007507,0.007512,...,0.007253,0.007254,0.007254,0.007254,0.007255,0.007255,0.007255,0.007255,0.007255,0.007255
新宿区大久保３丁目,0.159480,0.144070,0.129365,0.116050,0.104638,0.095437,0.088549,0.083876,0.081141,0.079934,...,0.093422,0.092664,0.090313,0.086255,0.080490,0.073142,0.064448,0.054731,0.044377,0.033802

In [ ]:
danger_indices[danger_indices.index.str.contains('新宿区')].sort_values('2022-08-31', ascending=False)[['2022-08-31', '2022-09-01', '2022-09-02']]

           2022-08-31  2022-09-01  2022-09-02
市区町丁
新宿区新宿４丁目     0.346421    0.353478    0.369594
新宿区西新宿８丁目    0.307571    0.313443    0.326999
新宿区内藤町       0.295792    0.301828    0.315578
新宿区新宿２丁目     0.282565    0.288289    0.301293
新宿区新宿１丁目     0.278745    0.284066    0.296465
...               ...         ...         ...
新宿区神楽坂５丁目    0.004878    0.004885    0.005055
新宿区箪笥町       0.004188    0.004125    0.004290
新宿区中町        0.003726    0.003674    0.003841
新宿区岩戸町       0.003401    0.003344    0.003485
新宿区細工町       0.003291    0.003220    0.003366

[131 rows x 3 columns]

In [ ]:
filtered_sorted_df = danger_indices[danger_indices.index.str.contains('新宿区')].sort_values('2022-08-31', ascending=False)[['2022-08-31', '2022-09-01', '2022-09-02']]

# Step 2: Flatten the '2022-08-31' column to get quantile boundaries
quantile_values = np.quantile(filtered_sorted_df['2022-08-31'], np.linspace(0, 1, 5))

# Step 3: Select rows corresponding to quantile boundaries
quantile_rows = filtered_sorted_df[filtered_sorted_df['2022-08-31'].isin(quantile_values)]

print(quantile_rows.index)

Index(['新宿区新宿４丁目', '新宿区上落合２丁目', '新宿区細工町'], dtype='object', name='市区町丁')

In [ ]:
locs = ['新宿区新宿４丁目', '新宿区市谷台町', '新宿区早稲田町', '新宿区細工町', '新宿区新宿３丁目', '新宿区歌舞伎町２丁目', '新宿区上落合２丁目']

In [ ]:
region = '新宿区新宿６丁目'
danger_indices_normalized.loc[list(predict_dicts[row.name].keys())]['2022-01-01'].nlargest(3).index.to_list()

['新宿区大久保１丁目', '新宿区北新宿２丁目', '新宿区北新宿１丁目']

In [ ]:
danger_indices[danger_indices.index.str.contains('新宿区')].sort_values('2022-08-31', ascending=False)[['2022-08-31', '2022-09-01', '2022-09-02']].loc[locs]

            2022-08-31  2022-09-01  2022-09-02
市区町丁
新宿区新宿４丁目      0.346421    0.353478    0.369594
新宿区市谷台町       0.023027    0.023188    0.023467
新宿区早稲田町       0.011476    0.010194    0.008898
新宿区細工町        0.003291    0.003220    0.003366
新宿区新宿３丁目      0.215575    0.219872    0.229726
新宿区歌舞伎町２丁目    0.227375    0.231802    0.241834
新宿区上落合２丁目     0.033184    0.031537    0.029929

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
danger_indices_flattened = danger_indices.values.flatten().reshape(-1, 1)

danger_indices_scaled_flattened = scaler.fit_transform(danger_indices_flattened)

danger_indices_normalized = pd.DataFrame(danger_indices_scaled_flattened.reshape(danger_indices.shape), columns=danger_indices.columns, index=danger_indices.index)

In [ ]:
danger_indices_normalized.to_csv('final_data/danger_indices.csv', index=True)

In [ ]:
danger_indices_normalized

,2022-01-01,2022-01-02,2022-01-03,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-08,2022-01-09,2022-01-10,...,2022-12-22,2022-12-23,2022-12-24,2022-12-25,2022-12-26,2022-12-27,2022-12-28,2022-12-29,2022-12-30,2022-12-31
市区町丁,,,,,,,,,,,,,,,,,,,,,
新宿区袋町,0.010589,0.010601,0.010615,0.010631,0.010647,0.010661,0.010672,0.010677,0.010672,0.010657,...,0.010563,0.010571,0.010577,0.010583,0.010587,0.010589,0.010591,0.010591,0.010591,0.010590
新宿区津久戸町,0.011867,0.011880,0.011899,0.011924,0.011954,0.011987,0.012020,0.012051,0.012075,0.012086,...,0.011867,0.011875,0.011882,0.011887,0.011891,0.011894,0.011896,0.011896,0.011896,0.011895
新宿区新宿３丁目,0.419876,0.385313,0.351555,0.320168,0.292238,0.268416,0.248984,0.233874,0.222661,0.214602,...,0.220847,0.220040,0.215622,0.206904,0.193520,0.175497,0.153264,0.127609,0.099596,0.070472
新宿区下落合３丁目,0.067306,0.076465,0.085396,0.093675,0.101000,0.107216,0.112306,0.116361,0.119532,0.121962,...,0.117528,0.112370,0.106179,0.099472,0.092728,0.086336,0.080567,0.075570,0.071383,0.067956
豊島区池袋１丁目,0.085132,0.107205,0.128300,0.147232,0.163215,0.175920,0.185449,0.192230,0.196881,0.200029,...,0.195297,0.183984,0.170324,0.155457,0.140451,0.126179,0.113253,0.102013,0.092552,0.084767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
豊島区池袋本町４丁目,0.063342,0.085841,0.107237,0.126319,0.142285,0.154812,0.164012,0.170339,0.174439,0.176989,...,0.173592,0.161102,0.146567,0.131132,0.115840,0.101523,0.088742,0.077784,0.068695,0.061333
新宿区改代町,0.012633,0.012633,0.012633,0.012634,0.012635,0.012637,0.012639,0.012641,0.012644,0.012647,...,0.012636,0.012636,0.012636,0.012636,0.012636,0.012636,0.012636,0.012636,0.012636,0.012636
新宿区市谷船河原町,0.014389,0.014281,0.014146,0.013991,0.013826,0.013669,0.013542,0.013471,0.013488,0.013626,...,0.014355,0.014366,0.014375,0.014383,0.014388,0.014392,0.014394,0.014394,0.014394,0.014393
新宿区天神町,0.010720,0.010795,0.010867,0.010933,0.010989,0.011035,0.011071,0.011098,0.011115,0.011123,...,0.010740,0.010740,0.010741,0.010741,0.010742,0.010742,0.010742,0.010742,0.010742,0.010742
新宿区大久保３丁目,0.236137,0.213319,0.191546,0.171831,0.154933,0.141310,0.131112,0.124192,0.120142,0.118355,...,0.138327,0.137204,0.133723,0.127714,0.119178,0.108299,0.095425,0.081039,0.065707,0.050049

In [ ]:
df_flattened = danger_indices_normalized.values.flatten()

# Calculate the boundaries for 3 quantiles
quantile_boundaries = np.quantile(df_flattened, [0, 1/5, 4/5, 1])

print("Quantile Boundaries:", quantile_boundaries)

Quantile Boundaries: [0.         0.03074196 0.20789261 1.        ]