In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/My Drive/Crime Analysis')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Data Preprocessing

For data from 2024, group by month, then scale by the number of cases observed in a month (region df)<br>
For data from 2023 and earlier, group by year, then scale by the number of cases observed in a year (region df)

### 2024

In [ ]:
df_2024 = pd.DataFrame()

for i in range(1, 7):
    region_df = pd.read_csv(f'data/region/region_2024_{i}.csv')
    region_df['month'] = i
    df_2024 = pd.concat([df_2024, region_df], axis=0)

In [ ]:
na_count = df_2024.groupby(['month', '市区町丁'])['非侵入窃盗計'].sum().unstack().isna().sum().sort_values(ascending=False)
df_2024_timeseries = df_2024.groupby(['month', '市区町丁'])['非侵入窃盗計'].sum().unstack().T.loc[na_count.index[na_count == 0]]

In [ ]:
df_2024_timeseries

month            1       2        3        4        5        6
市区町丁
港区赤坂２丁目        0.0     1.0      1.0      3.0      5.0      6.0
豊島区池袋２丁目       9.0    17.0     22.0     36.0     45.0     59.0
足立区中央本町３丁目     1.0     1.0      1.0      1.0      1.0      1.0
足立区弘道１丁目       1.0     2.0      4.0      5.0      6.0      6.0
港区赤坂３丁目        1.0     4.0      9.0     18.0     19.0     21.0
...            ...     ...      ...      ...      ...      ...
新宿区新宿１丁目       3.0     6.0     10.0     15.0     17.0     21.0
新宿区新宿２丁目       6.0    11.0     16.0     24.0     35.0     41.0
新宿区新宿３丁目      55.0   101.0    153.0    197.0    243.0    291.0
新宿区新宿４丁目       2.0     4.0      9.0     13.0     16.0     20.0
２３区計        3625.0  6781.0  10064.0  13469.0  16988.0  20728.0

[2965 rows x 6 columns]

## 2023 and earlier

In [ ]:
df_2023earlier = pd.DataFrame()

for i in range(2019, 2023):
    region_df = pd.read_csv(f'data/region/region_{i}.csv')
    region_df['year'] = i
    df_2023earlier = pd.concat([df_2023earlier, region_df], axis=0)

In [ ]:
na_count_2023earlier = df_2023earlier.groupby(['year', '市区町丁'])['非侵入窃盗計'].sum().unstack().isna().sum().sort_values(ascending=False)
df_2023earlier_timeseries = df_2023earlier.groupby(['year', '市区町丁'])['非侵入窃盗計'].sum().unstack().T.loc[na_count_2023earlier.index[na_count_2023earlier == 0]]

In [ ]:
df_2023earlier_timeseries

year             2019     2020     2021     2022
市区町丁
渋谷区西原１丁目         26.0     16.0      8.0     11.0
港区台場２丁目          12.0     13.0      4.0      4.0
渋谷区上原３丁目          9.0      7.0      4.0      3.0
渋谷区西原２丁目          5.0      6.0      6.0      5.0
港区北青山３丁目         34.0     15.0     27.0     27.0
...               ...      ...      ...      ...
小平市花小金井南町２丁目      2.0      1.0      2.0      7.0
小平市花小金井南町１丁目     25.0     18.0      6.0      9.0
小平市美園町３丁目        11.0      7.0      4.0      4.0
小平市美園町２丁目        14.0     16.0     12.0      7.0
２３区計          52510.0  38984.0  34477.0  36882.0

[4792 rows x 4 columns]

In [ ]:
df_cases = pd.DataFrame()

for filename in os.listdir('data/case'):
    if filename.endswith('.csv'):
        df = pd.concat([df, pd.read_csv('data/case/' + filename)])